### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by Robert3141** [JulianEggers/julianeggers.github.io#1]
I'm very pleased with your dark theme app and after investigating it led me to your page. You mentioned that the source code of the app is available on your GitHub however the links return an error 404 page not found. I'm quite interested in how these apps work. Many thanks in advance.

**Comment by JulianEggers** [comment]
Hey,
nice to hear that you like my app. My main-web page was not meant to be
public since I am currently working on it. I am going to hide it until I
finished working on it. I decided to make the repository private since the
app got a lot of attention recently and I was not 100% sure
weather everything I committed should be shown to the public.

To answer your question:
Activating the dark mode for an entire android device is quite simple. You
just have to use the UiModeManager (
https://developer.android.com/reference/android/app/UiModeManager) and call
uiModeManager.setNightMode(UiModeManager.MODE_NIGHT_YES)
~Julian
